# Generated by Django 4.2.11 on 2024-04-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('num_ticket', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=512)),
                ('parametro', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('obs', models.CharField(max_length=512)),
                ('data', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('horario', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSoticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('faltas', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_soticon', to='gerUsuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado', models.BooleanField(default=False)),
                ('reservado', models.BooleanField(default=False)),
                ('posicao_fila', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets_posicao', to='soticon.posicaofila')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets_rota', to='soticon.rota')),
                ('user_soticon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soticon', to='soticon.usersoticon')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('user_soticon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strike_user_soticon', to='soticon.usersoticon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('obs', models.CharField(max_length=512)),
                ('strike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa_strike', to='soticon.strike')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
