# Generated by Django 4.2.11 on 2024-09-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soticon', '0004_alter_tickets_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.UniqueConstraint(fields=('rota', 'posicao_fila'), name='unique_rota_posicao_constraint'),
        ),
    ]
