# Generated by Django 4.2.11 on 2024-09-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soticon', '0005_tickets_unique_rota_posicao_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='faltante',
            field=models.BooleanField(default=False),
        ),
    ]
