# Generated by Django 4.2.11 on 2024-04-11 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=60)),
                ('tel', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_contato', to='gerUsuarios.contato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('logradouro', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=30, null=True)),
                ('num_casa', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setor_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_user_setor', to='gerUsuarios.setor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_contato', to='gerUsuarios.contato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_empresa', to='gerUsuarios.empresa')),
                ('setores', models.ManyToManyField(through='gerUsuarios.Setor_User', to='gerUsuarios.setor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_tipo', to='gerUsuarios.tipo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AddField(
            model_name='setor_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_user_user', to='gerUsuarios.user'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('matricula', models.CharField(max_length=19, unique=True)),
                ('validade', models.DateField(null=True)),
                ('expedicao', models.DateField()),
                ('tipo_matricula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipo_matricula', to='gerUsuarios.tipo_matricula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matricula_user', to='gerUsuarios.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contato',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contato_endereco', to='gerUsuarios.endereco'),
        ),
        migrations.CreateModel(
            name='Alteracao_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisado', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('antigo_contato', models.IntegerField(null=True)),
                ('novo_contato', models.IntegerField(null=True)),
                ('user_analista', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alteracao_user_user', to='gerUsuarios.user')),
            ],
        ),
    ]
