# Generated by Django 4.2.11 on 2024-04-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_contato', to='gerUsuarios.contato'),
        ),
        migrations.AlterField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_empresa', to='gerUsuarios.empresa'),
        ),
    ]
