# Generated by Django 4.2.11 on 2024-04-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alteracao_User',
        ),
    ]
