# Generated by Django 4.2.11 on 2024-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0002_delete_alteracao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
