# Generated by Django 4.2.11 on 2024-09-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0003_endereco_cidade_endereco_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='tipo_matricula',
        ),
    ]
