# Generated by Django 4.2.11 on 2024-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0004_alter_user_contato_alter_user_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ativo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
