# Generated by Django 4.2.11 on 2024-09-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0004_remove_matricula_tipo_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_Matricula',
        ),
    ]
