# Generated by Django 4.2.11 on 2024-09-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0005_delete_tipo_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
