# Generated by Django 4.2.11 on 2024-09-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0007_alter_empresa_nome_alter_setor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='contato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_contato', to='gerUsuarios.contato'),
        ),
    ]
