# Generated by Django 4.2.11 on 2024-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='passwordresetcode',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_code_user_constraint'),
        ),
    ]
