# Generated by Django 4.2.11 on 2024-09-12 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0010_passwordresetcode_unique_code_user_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
