# Generated by Django 4.2.11 on 2024-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0011_passwordresetcode_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123@invalidemail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
