# Generated by Django 4.2.11 on 2024-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='num_casa',
            field=models.IntegerField(null=True),
        ),
    ]
