# Generated by Django 4.2.11 on 2024-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0013_alter_endereco_cep_alter_endereco_num_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
    ]
