# Generated by Django 4.2.11 on 2024-11-01 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0016_alter_user_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='deficiencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios_deficiencia', to='gerUsuarios.deficiencia'),
        ),
    ]
