# Generated by Django 4.2.11 on 2024-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerUsuarios', '0017_deficiencia_user_deficiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.URLField(null=True),
        ),
    ]
