# Generated by Django 4.2.11 on 2024-07-02 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
