# Generated by Django 4.2.11 on 2024-11-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watt', '0002_leitura_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leitura',
        ),
    ]
